### ISSUE TITLE
FR: share results via social networks

### ISSUE THREAD

**Issue by aspiers** [denisk20/bullshit-bingo-champion#6]
I haven't tried this *awesome* project yet, but it seems like it doesn't yet support sharing of results of a bingo game with people via social networks.  Despite the obvious risks of getting fired by doing this, it's a feature we clearly need ;-)  So please consider this feature request.

**Comment by denisk20** [comment]
Implemented in 1.2, check it on Play Store!

**Comment by aspiers** [comment]
Woohoo, thanks a lot! :)
